import { WeaponType } from './forms/weapon-form/weapon-form';

export interface Card {
  name: string,
  movement : string,
  APL: number,
  GA: number,
  DF: number,
  save : number,
  wounds: number,
  weapons?: Weapon[],
  abilities?: Abilities[],
  abilitiesFull: string,
  uniqueActions?: UniqueActions[]
  equipment?:Equipment,
  ploy?:Ploy;
  tacops?:Tacops;
  width?:number,
  height?:number,
  svgBckg?:string
}

// Generated by https://quicktype.io

export interface Ploy {
  factionid: string;
  killteamid: string;
  ployid: string;
  ployname: string;
  ploytype: string;
  CP: string;
  description: string;
}

export interface UniqueActions {
  factionid: string;
  killteamid: string;
  fireteamid: string;
  opid: string;
  uniqueactionid: string;
  title: string;
  description: string;
  AP: number;
}

export interface Weapon {
  weaponType: WeaponType;
}

interface Abilities {
  factionid: string;
  killteamid: string;
  fireteamid: string;
  opid: string;
  abilityid: string;
  title: string;
  description: string;
}

export interface Weapon {
  factionid: string;
  killteamid: string;
  fireteamid: string;
  opid: string;
  wepid: string;
  wepseq: number;
  wepname: string;
  weptype: string;
  isdefault: number;
  profiles: WeaponProfile[];
  isselected: boolean;
}

export interface WeaponProfile {
  factionid: string;
  killteamid: string;
  fireteamid: string;
  opid: string;
  wepid: string;
  profileid: string;
  name: string;
  A: string;
  BS: string;
  D: string;
  SR: string;
}

export interface Equipment {
  factionid: string;
  killteamid: string;
  eqid: string;
  eqname: string;
  eqdescription: string;
  eqpts: string;
  eqtype: string;
  eqvar1: string;
  eqvar2: string;
  eqvar3: string;
  eqvar4: string;
  eqcategory: string;
  fireteamid: string;
  opid: string;
  eqseq: number;
}

export interface Tacops {
  tacopid: string
  archetype: string
  tacopseq: number
  title: string
  description: string
}

